version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: base_uco
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: uco
      POSTGRES_PASSWORD: uco3023
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: